---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
  - name: bosh-master
  - name: bosh-cli
  - name: version
  - name: release-tarball

outputs:
  - name: bosh-master-with-final

params:
  BLOBSTORE_ACCESS_KEY_ID: replace-me
  BLOBSTORE_SECRET_ACCESS_KEY: replace-me

run:
  path: bosh-master/ci/tasks/finalize-bosh-release.sh
